name: swiggy
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
#  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.7.2
  http: any
  provider: ^6.1.5
  flutter_sliding_toast: any
  shared_preferences: ^2.2.3
#  syncfusion_flutter_charts: any
#  get_storage: any
  image_picker: ^1.1.2
#  permission_handler: ^12.0.1
#  multi_image_picker_view: ^3.0.0
#  flutter_plugin_android_lifecycle: ^2.0.17
#  geolocator: ^14.0.2
#  geocoding: ^3.0.0
#  flutter_image_compress: ^2.4.0
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
     - family: bold
       fonts:
          - asset: assets/fonts/Poppins-Bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: regular
       fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

