// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa073djgPJ2jzjHiuqPXy6m5CFJScbyBU',
    appId: '1:390770144365:web:3f0eff25901cc93ad4fb64',
    messagingSenderId: '390770144365',
    projectId: 'chatroom-2e5b7',
    authDomain: 'chatroom-2e5b7.firebaseapp.com',
    databaseURL: 'https://chatroom-2e5b7.firebaseio.com',
    storageBucket: 'chatroom-2e5b7.firebasestorage.app',
    measurementId: 'G-SF47V8J9TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcA60QS5R7PPmolUhBD9wVrv1fB3dX6Nk',
    appId: '1:390770144365:android:6a518f31b4fd92aad4fb64',
    messagingSenderId: '390770144365',
    projectId: 'chatroom-2e5b7',
    databaseURL: 'https://chatroom-2e5b7.firebaseio.com',
    storageBucket: 'chatroom-2e5b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaE23Ug04wxg97FtsMv0cNB7cWd2q38uA',
    appId: '1:390770144365:ios:721eba43e046c759d4fb64',
    messagingSenderId: '390770144365',
    projectId: 'chatroom-2e5b7',
    databaseURL: 'https://chatroom-2e5b7.firebaseio.com',
    storageBucket: 'chatroom-2e5b7.firebasestorage.app',
    iosBundleId: 'com.example.swiggy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaE23Ug04wxg97FtsMv0cNB7cWd2q38uA',
    appId: '1:390770144365:ios:721eba43e046c759d4fb64',
    messagingSenderId: '390770144365',
    projectId: 'chatroom-2e5b7',
    databaseURL: 'https://chatroom-2e5b7.firebaseio.com',
    storageBucket: 'chatroom-2e5b7.firebasestorage.app',
    iosBundleId: 'com.example.swiggy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa073djgPJ2jzjHiuqPXy6m5CFJScbyBU',
    appId: '1:390770144365:web:88e11a2f61ec4513d4fb64',
    messagingSenderId: '390770144365',
    projectId: 'chatroom-2e5b7',
    authDomain: 'chatroom-2e5b7.firebaseapp.com',
    databaseURL: 'https://chatroom-2e5b7.firebaseio.com',
    storageBucket: 'chatroom-2e5b7.firebasestorage.app',
    measurementId: 'G-NSW14B8H5V',
  );
}
